export default {
  images: [
    {
      title: '045',
      dateUploaded: '16.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/045.png', import.meta.url).href,
    },
    {
      title: '044',
      dateUploaded: '15.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/044.png', import.meta.url).href,
    },
    {
      title: '043',
      dateUploaded: '14.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/043.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/043.mp4', import.meta.url).href,
    },
    {
      title: '042',
      dateUploaded: '13.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/042.png', import.meta.url).href,
    },
    {
      title: '041',
      dateUploaded: '12.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/041.png', import.meta.url).href,
    },
    {
      title: '040',
      dateUploaded: '10.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/040.png', import.meta.url).href,
    },
    {
      title: '039',
      dateUploaded: '9.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/039.png', import.meta.url).href,
    },
    {
      title: '038',
      dateUploaded: '8.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/038.png', import.meta.url).href,
    },
    {
      title: '037',
      dateUploaded: '7.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/037.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/037.mp4', import.meta.url).href,
    },
    {
      title: '036',
      dateUploaded: '6.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/036.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/036.mp4', import.meta.url).href,
    },
    {
      title: '035',
      dateUploaded: '5.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/035.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/035.mp4', import.meta.url).href,
    },
    {
      title: '034',
      dateUploaded: '4.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/034.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/034.mp4', import.meta.url).href,
    },
    {
      title: '033',
      dateUploaded: '3.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/033.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/033.mp4', import.meta.url).href,
    },

    {
      title: '032',
      dateUploaded: '2.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/032.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/032.mp4', import.meta.url).href,
    },
    {
      title: '031',
      dateUploaded: '1.12.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/031.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/031.mp4', import.meta.url).href,
    },
    {
      title: '030',
      dateUploaded: '30.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/030.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/030.mp4', import.meta.url).href,
    },
    {
      title: '029',
      dateUploaded: '29.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/029.png', import.meta.url).href,
    },
    {
      title: '028',
      dateUploaded: '28.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/028.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/028.mp4', import.meta.url).href,
    },
    {
      title: '027',
      dateUploaded: '27.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/027.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/027.mp4', import.meta.url).href,
    },
    {
      title: '026',
      dateUploaded: '26.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/026.png', import.meta.url).href,
    },
    {
      title: '025',
      dateUploaded: '25.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/025.png', import.meta.url).href,
    },
    {
      title: '024',
      dateUploaded: '24.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/024.png', import.meta.url).href,
    },
    {
      title: '023',
      dateUploaded: '23.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/023.png', import.meta.url).href,
    },
    {
      title: '022',
      dateUploaded: '22.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/022.png', import.meta.url).href,
    },
    {
      title: '021',
      dateUploaded: '19.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/021.png', import.meta.url).href,
    },
    {
      title: '020',
      dateUploaded: '19.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/020.png', import.meta.url).href,
    },
    {
      title: '019',
      dateUploaded: '19.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/019.png', import.meta.url).href,
    },
    {
      title: '018',
      dateUploaded: '18.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/018.png', import.meta.url).href,
    },
    {
      title: '017',
      dateUploaded: '17.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/017.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/017.mp4', import.meta.url).href,
    },
    {
      title: '016',
      dateUploaded: '16.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/016.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/016.mp4', import.meta.url).href,
    },
    {
      title: '015',
      dateUploaded: '15.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/015.png', import.meta.url).href,
    },
    {
      title: '014',
      dateUploaded: '14.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/014.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/014.mp4', import.meta.url).href,
    },
    {
      title: '013',
      dateUploaded: '13.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/013.png', import.meta.url).href,
    },
    {
      title: '012',
      dateUploaded: '12.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/012.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/012.mp4', import.meta.url).href,
    },
    {
      title: '011',
      dateUploaded: '11.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/011.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/011.mp4', import.meta.url).href,
    },
    {
      title: '010',
      dateUploaded: '10.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/010.png', import.meta.url).href,
    },
    {
      title: '009',
      dateUploaded: '09.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/009.png', import.meta.url).href,
    },
    {
      title: '008',
      dateUploaded: '08.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/008.png', import.meta.url).href,
    },
    {
      title: '007',
      dateUploaded: '07.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/007.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/007.mp4', import.meta.url).href,
    },
    {
      title: '006',
      dateUploaded: '06.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/006.png', import.meta.url).href,
    },
    {
      title: '005',
      dateUploaded: '05.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/005.png', import.meta.url).href,
    },
    {
      title: '004',
      dateUploaded: '04.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/004.png', import.meta.url).href,
      mp4: new URL('./assets/mp4/0000/004.mp4', import.meta.url).href,
    },
    {
      title: '003',
      dateUploaded: '03.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/003.png', import.meta.url).href,
    },
    {
      title: '002',
      dateUploaded: '02.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/002.png', import.meta.url).href,
    },
    {
      title: '001',
      dateUploaded: '01.11.21',
      madeWith: 'P5.JS',
      categories: ['code', 'graphic'],
      url: new URL('./assets/img/0000/001.png', import.meta.url).href,
    },
  ],
}
